name: mongodb-reservation

replicas: 1

ports:
  - port: 27022
    targetPort: 27017

container:
  dockerRegistry: registry.domain.local
  image: mongo
  imageVersion: cosigned
  name: hotel-reserv-reservation-mongo
  ports:
  - containerPort: 27017
