name: mongodb-profile

replicas: 1

ports:
  - port: 27019
    targetPort: 27017
 
container:
  dockerRegistry: registry.domain.local
  image: mongo
  imageVersion: cosigned
  name: hotel-reserv-profile-mongo
  ports:
  - containerPort: 27017
